### ISSUE TITLE
Background Image from Less index not rendering on my machine

### ISSUE THREAD

**Issue by CintBX** [ApolloXI14/exodus#11]
__File:__ /less/index.less

__Code in Question__
```
html body {
	height: 100%;
	background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(../www/img/background/background.jpg) no-repeat center center;
	background-size: cover;
	background-attachment: fixed;
	background-position: center;
	background-repeat: no-repeat;
	background-size: cover;
}
```

**Comment by ApolloXI14** [comment]
Let's meet this week for this.

**Comment by ApolloXI14** [comment]
Getting Zoom on my dev machine this week to meet.

**Comment by ApolloXI14** [comment]
In the meantime, please double check the following packages in package.json, and npm install them if necessary:

"less"
"less-loader"
"url-loader" 
"resolve-url-loader"

**Comment by ApolloXI14** [comment]
This was a Windows OS issue. The local dev and prod environment works on Linux.

Also, the README instructions were also unclear, so I updated it (031233929c607629a2b7721f6af200c2f04decc8).

Closing.
