### ISSUE TITLE
Replace anchor tags in World.js with react-router-dom and <Link>

### ISSUE THREAD

**Issue by ApolloXI14** [ApolloXI14/exodus#15]
Steps to reproduce:

1) Click on "World" picture link
2) Click on "U.S.B" or "Exodus"

Dev server: Browser refreshes and PhotoNavbar does not disappear
Prod server: 404, because the server tries to load a real "earth.html" or "exodus.html", which does not exist

This behavior is happening because "World.js" component is currently coded to navigate with anchor tags instead of using the routing system, which causes a browser refresh and causes other elements to not disappear

"react-router-dom" must be imported and anchor tags must be replaced with `<Link>` to keep the application SPA and maintain styling.

Please see "PhotoNavbar.js" component for reference, and refer to this if needed: https://reactrouter.com/web/guides/quick-start

**Dev server (npm run start)**

![Screenshot_20210324_125201](https://user-images.githubusercontent.com/72114670/112356217-c1dddd00-8ca4-11eb-8339-db3891f61fbf.png)
![Screenshot_20210324_125153](https://user-images.githubusercontent.com/72114670/112356223-c1dddd00-8ca4-11eb-826a-e69e614895c8.png)
![Screenshot_20210324_124827](https://user-images.githubusercontent.com/72114670/112356226-c2767380-8ca4-11eb-9950-bc2d0234034b.png)

**Prod server (npm run build && npm run prod-start)**

![Screenshot_20210324_133858](https://user-images.githubusercontent.com/72114670/112358053-598ffb00-8ca6-11eb-8ca4-48b90ef1cda6.png)
![Screenshot_20210324_133819](https://user-images.githubusercontent.com/72114670/112358054-5a289180-8ca6-11eb-8c30-68c4911ca504.png)

**Comment by CintBX** [comment]
Replaced anchor tags with react-router-dom Links.
Issue fixed when navigating through the app, but bug still exists on page refresh.  Will leave this issue open for now.

**Comment by CintBX** [comment]
Closing because of our SCRUM meeting in which we agreed to let the bug be for now (until implementing something to handle page refresh later on)
