### ISSUE TITLE
Background images are set directly in component instead of less

### ISSUE THREAD

**Issue by ApolloXI14** [ApolloXI14/exodus#17]
Please explain why you decided to attach your background images on the "style" attribute, instead of using the less stylesheet that is already included? Was it because you were using Windows before, and therefore the less wasn't working?

Components in question are: Earth, Exodus, MapModals, RaceModals

**Example**:

![Screenshot_20210404_182538](https://user-images.githubusercontent.com/72114670/113523479-b37da400-9575-11eb-8967-4975f6d2f26d.png)

**Comment by CintBX** [comment]
Correct, I placed them in the components in the meantime until we figured out the less issue. 
Creating branch and PR shortly.

**Comment by ApolloXI14** [comment]
@CintBX Please link PRs to issues, so that merging the PR will auto-close the issue.
