### ISSUE TITLE
Story: Create "Contact" page

### ISSUE THREAD

**Issue by ApolloXI14** [ApolloXI14/exodus#2]
Story objective: Create "Contact" page

Acceptance criteria:

1. "Contact" header
2. Background
3. Body text

![Screenshot_20210117_123611](https://user-images.githubusercontent.com/72114670/104851070-a8916c80-58c0-11eb-8b83-2d2eabe99df5.png)

**Comment by CintBX** [comment]
Will take ideas I had from Chris' portfolio site for create this page. Including:
- Links to all his socials
- Incorporate EmailJS library to create a form that people can fill out that, upon submission, emails Chris directly.
