### ISSUE TITLE
BLOCKED BY SSR: World main page needs reformatting

### ISSUE THREAD

**Issue by CintBX** [ApolloXI14/exodus#21]
Because of my use of image positioning (absolute) the screen is a little buggy.
For example I was not able to add text properly, and right now when you scroll down, the background gets cut off and there is white space at the bottom of the screen.

**Comment by CintBX** [comment]
Also: The use of image positioning interfered with my attempt to create a Footer.

Will reformat or completely redo in a way that does not introduce bugs

**Comment by ApolloXI14** [comment]
Implementing NextJS will require a style refactor, so let's revisit this after that.

**Comment by CintBX** [comment]
Closing due to removal of World main page
