### ISSUE TITLE
BLOCKED BY SSR: Break on page refresh

### ISSUE THREAD

**Issue by CintBX** [ApolloXI14/exodus#29]
Photonavbar appears on the other pages when you f5 refresh

**Comment by ApolloXI14** [comment]
When making a "bug" issue, please include exact steps to reproduce, screenshots, and label the issue as "bug". @CintBX

**Comment by CintBX** [comment]
Steps to reproduce:
~ npm run start
~ localhost:8000
~ navigate to any page
~ press F5 refresh

Looks like:
![stories_page_bug1](https://user-images.githubusercontent.com/36093705/126206269-25860c88-77e1-4526-a136-9435fd799d65.png)

when refresh
![stories_page_bug2](https://user-images.githubusercontent.com/36093705/126206306-f43af5a9-9724-4ec8-ba8d-5240b016ec2f.png)

**Comment by ApolloXI14** [comment]
Thanks for the steps. I reproduced it. Blocking until SSR refactor.

**Comment by CintBX** [comment]
This issue can be closed.  F5 refresh no longer breaks
