### ISSUE TITLE
BLOCKED BY SSR: Stories page has incorrect background when accessed through top nav bar

### ISSUE THREAD

**Issue by CintBX** [ApolloXI14/exodus#31]
When cycling through the navlinks, sometimes the background image on Story page breaks for no reason I can see yet

**Comment by ApolloXI14** [comment]
When making a "bug" issue, please include exact steps to reproduce, screenshots, and label the issue as "bug". @CintBX

**Comment by CintBX** [comment]
Steps tp repoduce:
1 npm run start
2 localhost:8000
3 navigate to World, Gallery or Contact page (any of them) 
4 then navigate to Story page via the navbar directly from one of the pages above to view the broken version of Story page

Note: accessing Story page directly from the home page does not produce this bug

Looks like:
![stories_page_bug](https://user-images.githubusercontent.com/36093705/126205520-e99d7a37-2377-4df6-8f1b-fe06cdced7f8.png)

**Comment by ApolloXI14** [comment]
Thanks for the steps. I was able to reproduce. The specific issue is the correct background not loading through the top nav bar. Will revisit during/after SSR refactor.

**Comment by CintBX** [comment]
Closing this due to the fact that this no longer occurs (thanks to NextJS refactor)
