### ISSUE TITLE
BLOCKED BY SSR: Story: Create "Greetings" page

### ISSUE THREAD

**Issue by ApolloXI14** [ApolloXI14/exodus#4]
Story objective: Create "Greetings" page

Four main sections:

U.S.B. (Inactive), N.I.O. Suits, Science vs. Magic, DATABASE (Inactive)

Acceptance criteria:

1. Make "Greetings" for all four sections
2. Link to "N.I.O. Suits" and "Science vs Magic" sections, and display text

**Comment by CintBX** [comment]
This story is linked to World story, so it can be closed.
